[project]
name = "bachelor-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.12.0",
    "datasets>=4.8.5",
    "flash-attn>=2.8.3",
    "jiwer>=4.0.0",
    "librosa>=0.11.0",
    "matplotlib>=3.10.8",
    "openai-whisper>=20250625",
    "pandas>=3.0.1",
    "peft>=0.18.1",
    "protobuf>=7.34.0",
    "qwen-asr>=0.0.6",
    "seaborn>=0.13.2",
    "tensorboard>=2.20.0",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
    "torchcodec>=0.12.0",
    "torchvision>=0.25.0",
    "transformers>=4.57.6",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchaudio = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv]
no-build-isolation-package = ["flash-attn"]
